gicar:
 build: ./gicarAppJava/
 links:
  - demo
 ports:
  - 80:80
 environment:
  PS_IP: 169.50.103.27
  AgentConfigDocker: a6-demoFORM
  ContainerHostName: [nom del contenidor]
  AGENTNAME: a6-demoform,[nom de domini.gencat.cat]
  HCOGICAR: a6
  GICARUSER: registre
  GICARPWD: registre
  APPSERVER_PORT_8080_TCP_ADDR: demo
  APPSERVER_PORT_8080_TCP_PORT: 8080 
  context: canigoJSF
 volumes:
  - /home/canigo/Documents/workspace-sts-3.7.1.RELEASE/demo-JEE-AppJava/target/canigoJSF-static:/var/www/html/canigoJSF
db:
  build: ./bbdd/
  ports:
    - 3306:3306
  environment:
    MYSQL_USER : user
    MYSQL_PASSWORD : password
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: demo
  volumes:
   - /home/canigo/Documents/workspace-sts-3.7.1.RELEASE/demo-JEE-AppJava/mysql-datadir:/var/lib/mysql
demo:
  build: ./app/
  links:
    - db:mybbdd
  volumes:
   - /home/canigo/Documents/workspace-sts-3.7.1.RELEASE/demo-JEE-AppJava/target/canigoJSF-dynamic:/opt/tomcat/webapps/canigoJSF
  ports:
   - 8080:8080
   - 8000:8000

